# Dataset Configuration

# Data settings
data:
    variants: ["node_level", "global", "combined"]
    default_variant: "node_level"

# Graph settings
graph:
    num_nodes: 30
    types: ["BA", "ER", "NW"]

# Feature dimensions
features:
    node_level:
        dimension: 6
    global:
        dimension: 906  # 900 (adjacency) + 6 (features)
    combined:
        dimension: 36   # 30 (nodes) + 6 (features)

# Processing settings
processing:
    normalize_features: false # Features are already normalized during generation
    temporal_window: 10
    stride: 1

# Training settings
training:
    batch_size: 32
    num_workers: 4
    train_ratio: 0.7
    val_ratio: 0.15
