# GRAPH GENERATION PARAMETERS
common:
  nodes: 20            # Number of nodes in each graph
  seq_len: 200         # Length of each sequence
  min_segment: 30      # Minimum length of each segment
  min_changes: 1       # Minimum number of change points
  max_changes: 3       # Maximum number of change points

# BARABASI-ALBERT PARAMETERS
ba:
  edges: 3             # Initial number of edges per node
  min_edges: 2         # Minimum edges for parameter changes
  max_edges: 5         # Maximum edges for parameter changes

# ERDOS-RENYI PARAMETERS
er:
  p: 0.15             # Initial probability of edge creation
  min_p: 0.1          # Minimum probability for parameter changes
  max_p: 0.2          # Maximum probability for parameter changes

# NEWMAN-WATTS PARAMETERS
nw:
  k: 4                 # Initial number of nearest neighbors
  min_k: 2             # Minimum k for parameter changes
  max_k: 6             # Maximum k for parameter changes
  p: 0.2               # Initial rewiring probability
  min_p: 0.1           # Minimum probability for parameter changes
  max_p: 0.3           # Maximum probability for parameter changes
