# src/configs/change_scenarios.yaml

# Specialized change scenarios for different network types
# These configurations produce the specific change types shown in Table 4 of the paper

# Stochastic Block Model (SBM) change scenarios
sbm:
  community_merge:
    description: "Communities become increasingly connected, eventually merging"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    num_blocks: 2
    intra_prob: 0.95  # High intra-community connectivity
    inter_prob: 0.01  # Start with very separate communities
    min_intra_prob: 0.8  # Keep high intra-community connectivity
    max_intra_prob: 0.95
    min_inter_prob: 0.01  # Start low
    max_inter_prob: 0.6   # End high (communities effectively merge)
    change_type: "inter_prob_increase"  # Focus change on inter-community connections
    
  density_change:
    description: "Overall density changes while community structure remains intact"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    num_blocks: 2
    intra_prob: 0.4  # Start with moderate density
    inter_prob: 0.05
    min_intra_prob: 0.3  # Allow density to decrease
    max_intra_prob: 0.9  # Or increase significantly
    min_inter_prob: 0.01
    max_inter_prob: 0.1  # Keep communities fairly separate
    change_type: "density_shift"  # Both intra and inter probabilities change proportionally
    
  mixed_changes:
    description: "Both community structure and density change simultaneously"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 2
    num_blocks: 2
    intra_prob: 0.7
    inter_prob: 0.05
    min_intra_prob: 0.3
    max_intra_prob: 0.95
    min_inter_prob: 0.01
    max_inter_prob: 0.5
    change_type: "mixed"  # Both community structure and density change

# Erdős-Rényi (ER) change scenarios
er:
  density_increase:
    description: "Overall network density increases"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    prob: 0.05  # Start with low density
    min_prob: 0.05
    max_prob: 0.4  # End with high density
    change_type: "increase"
    
  density_decrease:
    description: "Overall network density decreases"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    prob: 0.4  # Start with high density
    min_prob: 0.4
    max_prob: 0.05  # End with low density
    change_type: "decrease"

# Barabási-Albert (BA) change scenarios
ba:
  parameter_shift:
    description: "Change in preferential attachment parameter"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    m: 2  # Start with moderate attachment
    min_m: 1
    max_m: 6
    change_type: "m_shift"
    
  hub_addition:
    description: "Introduction of new nodes with high connectivity"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    m: 2
    min_m: 2
    max_m: 2  # Keep base parameter constant
    hub_injection: true  # Special flag to inject hub nodes
    hub_connections: 15  # Number of connections for hub nodes
    hub_count: 3  # Number of hub nodes to inject
    change_type: "hub_injection"

# Newman-Watts-Strogatz (NWS) change scenarios
nws:
  rewiring_increase:
    description: "Increased probability of random edge rewiring"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    k_nearest: 6  # Keep neighborhood size constant
    min_k: 6
    max_k: 6
    rewire_prob: 0.05  # Start with low rewiring
    min_prob: 0.05
    max_prob: 0.4  # End with high rewiring
    change_type: "rewiring_increase"
    
  k_parameter_shift:
    description: "Change in the initial neighborhood connection parameter k"
    seq_len: 200
    min_segment: 40
    min_changes: 1
    max_changes: 1
    k_nearest: 4  # Start with small neighborhoods
    min_k: 4
    max_k: 12  # End with large neighborhoods
    rewire_prob: 0.1  # Keep rewiring probability constant
    min_prob: 0.1
    max_prob: 0.1
    change_type: "k_shift"

# MIT Reality Dataset scenario
# Note: This requires the actual dataset and not synthetic generation
mit_reality:
  academic_events:
    description: "Academic calendar events causing network structural changes"
    dataset_path: "data/mit_reality.csv"  # Path to the dataset
    change_annotations: [23, 68, 94, 173, 234]  # Known change points from paper
    validation_window: 15  # Detection within this many days is considered correct 