# Linear Models Configuration
#
# This configuration file defines parameters for a change point detection experiment
# using linear equations and martingale-based analysis. The experiment analyzes how
# different linear equations behave before and after a change point, using SHAP
# (SHapley Additive exPlanations) values for interpretability.

equations:
  # Sets of linear equations in the form [slope, intercept] representing y = mx + b
  default:              
    - [2, 3]            # First equation: y = 2x + 3
    - [3, 3]            # Second equation: y = 3x + 3
    - [5, 8]            # Third equation: y = 5x + 8
    - [7, 2]            # Fourth equation: y = 7x + 2
  modified:             # Alternative set of equations for comparison
    - [1, 2]            # Modified equations with different slopes and intercepts
    - [2, 4]
    - [4, 6]
    - [6, 1]

scenarios:                # Different test scenarios to evaluate change detection
  # Each scenario defines:
  # - name: Descriptive name for the scenario
  # - equations: Which equation set to use (default or modified)
  # - change_point: Time instant where behavior changes
  # - thresholds: Detection thresholds for sum and average martingales
  
  default:
    name: "Default Scenario"
    equations: "default"  # Use default equation set
    change_point: 100     # Point where change occurs
    thresholds:
      sum: 50             # Threshold for sum of martingales
      avg: 12.5           # Threshold for average of martingales

  low_threshold:
    name: "Low Thresholds"
    equations: "default"
    change_point: 100
    thresholds:
      sum: 30             # Lower thresholds to test sensitivity
      avg: 7.5

  high_threshold:
    name: "High Thresholds"
    equations: "default"
    change_point: 100
    thresholds:
      sum: 70             # Higher thresholds to test specificity
      avg: 17.5

  modified:
    name: "Modified Equations"
    equations: "modified" # Test with alternative equation set
    change_point: 100
    thresholds:
      sum: 50
      avg: 12.5

  early_change:
    name: "Early Change Point"
    equations: "default"
    change_point: 50      # Test detection of early changes
    thresholds:
      sum: 50
      avg: 12.5

  late_change:
    name: "Late Change Point"
    equations: "default"
    change_point: 150     # Test detection of late changes
    thresholds:
      sum: 50
      avg: 12.5

visualization:
  save_plots: true        # Whether to save generated plots
  num_graph_samples: 5    # Number of samples to show in visualizations

shap:
  # SHAP analysis configuration for model interpretability
  background_samples: 10   # Number of background samples for SHAP computation
  compute_full_range: true # Whether to compute SHAP values for entire time range

time:
  total_instants: 200     # Total number of time points to analyze

paths:
  output:
    dir: "outputs/linear_models/"  # Directory for saving results

logging:
  level: "INFO"           # Logging level (DEBUG, INFO, WARNING, ERROR)
  file: "logs/linear_models.log"  # Log file location
