# Template Configuration File
# This template shows all possible configuration options with explanations

graph:
  # Erdős-Rényi random graph parameters
  erdos_renyi:
    nodes: 50                   # Number of nodes in the graph
    probabilities:
      initial: 0.4              # Initial edge probability
      changed: 0.7              # Edge probability after change point
    set1: 100                   # Number of graphs before change point
    set2: 100                   # Number of graphs after change point

  # Barabási-Albert scale-free network parameters
  barabasi_albert:
    nodes: 50                  # Number of nodes in the graph
    edges:
      initial: 3               # Initial number of edges per new node
      changed: 7               # Edges per node after change point
      null_model:              # Optional: null model parameters
        initial: 5
        changed: 5
    set1: 100                  # Number of graphs before change point
    set2: 100                  # Number of graphs after change point

  # Newman-Watts small-world network parameters
  newman_watts:
    nodes: 30                  # Number of nodes in the graph
    neighbors:
      initial: 4               # Initial nearest neighbors per node
      changed: 6               # Neighbors after change point
    rewiring_prob:
      initial: 0.1             # Initial rewiring probability
      changed: 0.3             # Rewiring probability after change point
    set1: 100                  # Number of graphs before change point
    set2: 100                  # Number of graphs after change point

analysis:
  centrality_metrics:
    - degree                  # Node degree centrality
    - betweenness             # Betweenness centrality
    - eigenvector             # Eigenvector centrality
    - closeness               # Closeness centrality
    - svd                     # Singular Value Decomposition
    - lsvd                    # Localized SVD
  
  parameters:
    threshold: 15            # Detection threshold
    detect_change: true      # Enable change point detection
    change_point: 101        # Known change point for evaluation
    test_size: 0.2           # Train/test split ratio
    random_state: 42         # Random seed for reproducibility
    model_threshold: 20      # Model-specific threshold
    epsilon: 0.8             # Epsilon parameter for algorithms
    trials: 20               # Number of trials to run
  
  labels:
    high: 20                 # High label value
    low: 1                   # Low label value
  
  plot_range:
    start: 0                 # Start index for plotting
    end: 200                 # End index for plotting

data_processing:
  save_intermediate: true     # Save intermediate results
  probability_threshold: 0.3  # Probability threshold for processing 

paths:
  data:
    dir: "./files"         # Directory for input data
    proximity_file: "./files/Proximity.csv"  # Input data file
  
  output:
    dir: "./outputs"       # Directory for output files

visualization:
  save_plots: true        # Whether to save plot outputs
  num_graph_samples: 5    # Number of graph samples to visualize

logging:
  level: "INFO"           # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "logs/anomaly_detection.log"  # Log file path
