# DATASET CONFIGURATION
dataset:
  num_sequences: 10
  seq_len: 50
  min_segment: 10
  min_changes: 1
  max_changes: 2

  graph_types: ["SBM"]  # Supported: ["BA", "ER", "NW", "SBM"]
  graph_params:
    nodes: 500

    # Stochastic Block Model (SBM) parameters
    sbm:
      num_blocks: 5        # Number of communities
      block_size_range:    # Range for block sizes
        min: 80
        max: 120
      edge_probabilities:  # Within and between community probabilities
        intra_block: 0.3   # Higher probability within communities
        inter_block: 0.05  # Lower probability between communities
      change_ranges:       # Ranges for probability changes
        intra:
          min: 0.25       # Minimum intra-community probability after change
          max: 0.35       # Maximum intra-community probability after change
        inter:
          min: 0.03       # Minimum inter-community probability after change
          max: 0.07       # Maximum inter-community probability after change

    # Barabasi-Albert (BA) parameters
    ba:
      initial_edges: 3     # Initial number of edges per new node
      edge_range:          # Range for edge parameter changes
        min: 2
        max: 5
      pref_exp: 1.0       # Preferential attachment exponent

    # Erdos-Renyi (ER) parameters
    er:
      prob_range:          # Range for edge probability
        initial: 0.1
        min: 0.05
        max: 0.15

    # Newman-Watts (NW) parameters
    nw:
      k_nearest: 4         # Number of nearest neighbors in ring lattice
      prob_range:          # Range for rewiring probability
        initial: 0.1
        min: 0.05
        max: 0.15

  # Feature extraction settings
  features:
    use_node_features: true
    normalize: true
    types:
      - common_neighbors
      - jaccard
      - adamic_adar
      - preferential_attachment
      - resource_allocation
      - degree_similarity
      - community_similarity
      - block_membership

  # Link prediction specific settings
  link_prediction:
    negative_sampling_ratio: 2.0
    edge_split_method: "community_aware"
    preserve_connectivity: true
    min_positive_degree: 5

  # Dataset split ratios
  split_ratio:
    train: 0.70
    val: 0.15
    test: 0.15

  # Output settings
  output:
    dir: "dataset/sbm_community"
    format: "h5"
    compression: true