# DATASET CONFIGURATION
dataset:
  # Number of sequences to generate per graph type
  num_sequences: 10

  # Types of graphs to generate
  graph_types: ["BA", "ER", "NW"]
  # BA: Barabasi-Albert (scale-free networks)
  # ER: Erdos-Renyi (random networks)
  # NW: Newman-Watts (small-world networks)

  # Feature extraction settings
  features:
    use_node_features: true  # If false, uses global features
    normalize: true
    types:  # List of features to extract (leave empty for all)
      - degree
      - betweenness
      - eigenvector
      - closeness
      - svd
      - lsvd

  # Dataset split ratios
  split_ratio:
    train: 0.7
    val: 0.15
    test: 0.15

  # Output settings
  output_dir: "dataset"
  save_format: "h5"  # Options: h5, npz
  compression: true