# DATASET CONFIGURATION
dataset:
  # Number of sequences to generate per graph type
  num_sequences: 20

  # Types of graphs to generate
  graph_types: ["BA", "ER", "NW"]
  # BA: Barabasi-Albert (scale-free networks)
  # ER: Erdos-Renyi (random networks)
  # NW: Newman-Watts (small-world networks)

  # Dataset split ratios
  split_ratio:
    train: 0.7
    val: 0.15
    test: 0.15

  # Output directory for the dataset
  output_dir: "dataset"