# GRAPH GENERATION PARAMETERS
common:
  min_n: 50            # Minimum number of nodes in each graph
  max_n: 100           # Maximum number of nodes in each graph
  min_seq_length: 150  # Minimum sequence length
  max_seq_length: 200  # Maximum sequence length
  min_segment: 30      # Minimum length between changes
  min_changes: 2       # Minimum number of change points
  max_changes: 4       # Maximum number of change points

# BARABASI-ALBERT PARAMETERS
ba:
  initial_edges: 5     # Initial number of edges
  min_edges: 3         # Minimum number of edges after change
  max_edges: 10        # Maximum number of edges after change (increased for more variety)

# ERDOS-RENYI PARAMETERS
er:
  initial_p: 0.1       # Initial p parameter
  min_p: 0.05          # Minimum p parameter after change (decreased for more variety)
  max_p: 0.25          # Maximum p parameter after change (increased for more variety)

# NEWMAN-WATTS PARAMETERS
nw:
  initial_k: 4         # Initial k parameter
  min_k: 2             # Minimum k parameter after change
  max_k: 8             # Maximum k parameter after change (increased for more variety)
  initial_p: 0.1       # Initial p parameter
  min_p: 0.05          # Minimum p parameter after change (decreased for more variety)
  max_p: 0.25          # Maximum p parameter after change (increased for more variety)
