# MARTINGALE TEST PARAMETERS
martingale:
  # Strangeness measure parameters
  strangeness:
    window_size: 10    # Size of sliding window
    n_neighbors: 5     # Number of nearest neighbors for density estimation
    
  # Martingale parameters
  epsilon: 0.8         # Betting parameter
  threshold: 30.0      # Detection threshold
  reset: true          # Reset martingale after each change point
  
  # Change point detection
  detection:
    min_interval: 20   # Minimum interval between change points
    window_size: 5     # Window size for smoothing

# VISUALIZATION PARAMETERS
visualization:
  colors: "husl"
  feature_names:
    - "degree"
    - "betweenness"
    - "eigenvector"
    - "closeness"
