# Training Configuration
paths:
  data_dir: "dataset"
  output_dir: "outputs"

data:
  # Sequence parameters
  window_size: 20
  stride: 5
  forecast_horizon: 10
  batch_size: 16
  
  # Feature selection
  use_centrality: true
  use_spectral: true
  enable_augmentation: false
  noise_level: 0.01
  
  # Dataset constants
  num_nodes: 100
  max_seq_length: 200
  min_seq_length: 161
  num_change_points: 2
  
  # Feature dimensions
  svd_dim: 2
  lsvd_dim: 16

model:
  # Model architecture
  hidden_dim: 32
  num_layers: 2
  dropout: 0.2
  
  # Feature processing
  use_node_features: true
  use_edge_features: true
  combine_features: "concat"
  
  # GNN parameters
  gnn_type: "gcn"
  attention_heads: 4
  
  # LSTM parameters
  lstm_layers: 2
  bidirectional: false
  
  # Training parameters
  learning_rate: 0.001
  weight_decay: 0.0001
  clip_grad_norm: 0.5

training:
  epochs: 1
  patience: 10
  val_interval: 1
  save_interval: 5
  
  # Loss function weights
  loss_weights:
    degree: 1.0
    betweenness: 1.0
    closeness: 1.0
    eigenvector: 1.0
    svd: 0.5
    lsvd: 0.5
    
  # Learning rate schedule
  lr_schedule:
    factor: 0.5
    patience: 5
    min_lr: 0.000001

  # Logging
  log_interval: 10
  tensorboard: true
