# src/algorithm.yaml

name: forecast_based_graph_cpd
version: 1.0
description: "Forecast-based Graph Structural Change Detection using Martingale Framework with Distribution-Aware Prediction"

# Trial configuration
trials:
  n_trials: 2  # Number of times to run the detector
  random_seeds: 99  # Optional list of seeds for reproducibility. If null, will generate random seeds
  aggregate_stats: true  # Whether to compute aggregate statistics across trials
  save_individual_trials: false  # Whether to save results from each individual trial

# Model configuration
model:
  type: "multiview"  # or "single_view"
  network: "sbm"  # choices: ["ba", "ws", "er", "sbm"]
  predictor:
    type: "adaptive"  # choices: ["adaptive", "auto", "statistical"]
    config:
      # AdaptiveDistributionAwarePredictor configuration
      n_history: 5  # Number of historical graphs to consider
      adaptive: true  # Enable adaptive prediction
      enforce_connectivity: true  # Maintain graph connectivity in predictions
      binary: true  # Use binary adjacency matrices
      spectral_reg: 0.4  # Spectral regularization parameter
      community_reg: 0.4  # Community structure regularization
      n_communities: 2  # Number of communities to consider
      temporal_window: 10  # Window size for temporal patterns
      distribution_reg: 0.3  # Distribution regularization parameter

# Detection parameters
detection:
  threshold: 60.0  # Detection threshold for martingale
  batch_size: 1000  # Batch size for multiview processing
  reset: true  # Reset martingales after detection
  max_window: null  # Maximum window size (null for adaptive)
  prediction_horizon: 5  # Number of steps to predict ahead
  
  # Betting function configuration
  betting_func_config:
    name: "power"  # Available options: power, exponential, mixture, constant, beta, kernel
    power:  # Parameters specific to the power betting function
      epsilon: 0.7
    exponential:
      lambd: 1.0  # Rate parameter controlling sensitivity
    mixture:
      epsilons: [0.5, 0.6, 0.7, 0.8, 0.9]  # List of sensitivity parameters
    constant: {}  # No parameters needed
    beta:
      a: 0.5  # Alpha parameter of Beta distribution
      b: 1.5  # Beta parameter of Beta distribution
    kernel:
      bandwidth: 0.1  # Bandwidth for Gaussian kernel
      past_pvalues: []  # List of past p-values (updated during runtime)

  # Distance configuration
  distance:
    measure: "euclidean"  # choices: ["euclidean", "mahalanobis", "manhattan", "cosine", "minkowski", "chebyshev"]
    p: 2.0  # Order for Minkowski distance

# Feature extraction
features:
  - mean_degree  # Average node degree
  - density  # Graph density
  - mean_clustering  # Average clustering coefficient
  - mean_betweenness  # Average betweenness centrality
  - mean_eigenvector  # Average eigenvector centrality
  - mean_closeness  # Average closeness centrality
  - max_singular_value  # Largest singular value
  - min_nonzero_laplacian  # Smallest non-zero Laplacian eigenvalue

# Output configuration
output:
  directory: "src/results"  # Output directory for results
  prefix: ""  # Prefix for output files
  save_predictions: true  # Save predicted graphs
  save_features: true  # Save extracted features
  save_martingales: true  # Save martingale values
  visualization:
    enabled: true  # Enable result visualization
    skip_shap: false  # Include SHAP value analysis
