# src/algorithm.yaml

name: forecast_based_graph_cpd
version: 1.0
description: "Forecast-based Graph Structural Change Detection using Martingale Framework with Distribution-Aware Prediction"


# Model configuration
model:
  type: "multiview"  # or "single_view"
  network: "sbm"  # choices: ["ba", "ws", "er", "sbm"]
  predictor:
    type: "adaptive"  # choices: ["adaptive", "auto", "statistical"]
    config:
      # AdaptiveDistributionAwarePredictor configuration
      n_history: 5  # Number of historical graphs to consider
      adaptive: true  # Enable adaptive prediction
      enforce_connectivity: true  # Maintain graph connectivity in predictions
      binary: true  # Use binary adjacency matrices
      spectral_reg: 0.4  # Spectral regularization parameter
      community_reg: 0.4  # Community structure regularization
      n_communities: 2  # Number of communities to consider
      temporal_window: 10  # Window size for temporal patterns
      distribution_reg: 0.3  # Distribution regularization parameter

# Detection parameters
detection:
  threshold: 60.0  # Detection threshold for martingale
  epsilon: 0.7  # Sensitivity parameter for martingale updates
  batch_size: 1000  # Batch size for multiview processing
  reset: true  # Reset martingales after detection
  max_window: null  # Maximum window size (null for adaptive)
  prediction_horizon: 5  # Number of steps to predict ahead
  betting_function: "power"  # choices: ["power", "exponential", "mixture", "constant", "beta", "kernel"]
  distance:
    measure: "euclidean"  # choices: ["euclidean", "mahalanobis", "manhattan", "cosine", "minkowski"]
    p: 2.0  # Order for Minkowski distance (only used when measure is "minkowski")

# Feature extraction
features:
  - mean_degree  # Average node degree
  - density  # Graph density
  - mean_clustering  # Average clustering coefficient
  - mean_betweenness  # Average betweenness centrality
  - mean_eigenvector  # Average eigenvector centrality
  - mean_closeness  # Average closeness centrality
  - max_singular_value  # Largest singular value
  - min_nonzero_laplacian  # Smallest non-zero Laplacian eigenvalue

# Output configuration
output:
  directory: "src/results"  # Output directory for results
  prefix: ""  # Prefix for output files
  save_predictions: true  # Save predicted graphs
  save_features: true  # Save extracted features
  save_martingales: true  # Save martingale values
  visualization:
    enabled: true  # Enable result visualization
    skip_shap: false  # Include SHAP value analysis
