# DATASET CONFIGURATION

dataset:
  num_sequences: 100      # total number of graph sequences in the dataset
  seq_len: 50            # length of each graph sequence
  min_segment: 5         # minimum segment length between changes
  min_changes: 3         # minimum number of changes per sequence
  max_changes: 4         # maximum number of changes per sequence

  graph_params:
    nodes: 38            # number of nodes in each graph (matching UCSB dataset)
    sbm:
      num_blocks: 4      # number of communities (blocks) in the graph
      block_size_range:   
        min: 8           # minimum size of a community
        max: 12          # maximum size of a community
      edge_probabilities: 
        intra_block: 0.7  # probability of connections within the same community
        inter_block: 0.1  # probability of connections between different communities
      change_ranges:      
        intra:            
          min: 0.5       # minimum intra-community edge probability after changes
          max: 0.8       # maximum intra-community edge probability after changes
        inter:            
          min: 0.05      # minimum inter-community edge probability after changes
          max: 0.15      # maximum inter-community edge probability after changes
  
  # Output settings
  output:
    dir: "data/SBM"      # directory to save the dataset
    format: "txt"        # file format for edge lists
